// <auto-generated />
namespace Eagles.LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< HEAD:Eagles.LMS/Migrations/202206200632260_carrer.Designer.cs
    public sealed partial class carrer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(carrer));
        
        string IMigrationMetadata.Id
        {
            get { return "202206200632260_carrer"; }
========
    public sealed partial class dsddui : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dsddui));
        
        string IMigrationMetadata.Id
        {
            get { return "202206200805444_dsddui"; }
>>>>>>>> 81614a28004a47b059657190ca8f09f092e312df:Eagles.LMS/Migrations/202206200805444_dsddui.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
